name: Jekyll site CI

on: 
  push:
    branches:
      - 'main'
      - 'dev'
  schedule:
      - cron:  '0 18 * * 1,2,3,4,5'  # Runs at 09:00 UTC on the 1st of every month    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: WhiteTheace2/autoupdatetest
      - name: Build
        run: |
          echo $(date +%F%n%T) >> log.txt
      - name: Commit files
        run: |
          git config --local user.email "84350295+WhiteTheace2@users.noreply.github.com"
          git config --local user.name "WhiteTheace2"
          git add -A
          git commit -m "auto update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
